[project]
name = "obs-waykey"
version = "0.2.0"
description = "OBS global shortcuts workaround for wayland using websocket"
readme = "README.md"
authors = [
  { name = "PolyCat", email = "polycat@tuta.io" }
]
requires-python = ">=3.9"
dependencies = [
  "obsws-python>=1.7.0,<2.0.0",
]

[project.optional-dependencies]
dev = [
  "mypy>=1.10.0,<2.0.0",
]

[project.scripts]
obs-waykey = "obs_waykey:ignite"

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
